# Butler Groceries Home Assistant Integration
# Sensors and automations for meal planning
# URL: https://groceries.butlerfamily.com

command_line:
  - sensor:
      name: "Butler Groceries Tonight"
      unique_id: butlergroceries_tonight
      command: 'curl -s "http://192.168.1.131:8080/api/ha/tonight"'
      value_template: "{{ value_json.state }}"
      json_attributes:
        - attributes
      scan_interval: 300
      icon: mdi:silverware-fork-knife

  - sensor:
      name: "Butler Groceries Week"
      unique_id: butlergroceries_week
      command: 'curl -s "http://192.168.1.131:8080/api/ha/week-summary"'
      value_template: "{{ value_json.state }}"
      json_attributes:
        - attributes
      scan_interval: 600
      icon: mdi:calendar-week

  - sensor:
      name: "Butler Groceries Shopping"
      unique_id: butlergroceries_shopping
      command: 'curl -s "http://192.168.1.131:8080/api/ha/shopping-count"'
      value_template: "{{ value_json.state }}"
      json_attributes:
        - attributes
      scan_interval: 120
      icon: mdi:cart

  - sensor:
      name: "Butler Groceries Stats"
      unique_id: butlergroceries_stats
      command: 'curl -s "http://192.168.1.131:8080/api/ha/stats"'
      value_template: "{{ value_json.state }}"
      json_attributes:
        - attributes
      scan_interval: 3600
      icon: mdi:chart-bar

automation:
  - id: butlergroceries_dinner_reminder
    alias: "Butler Groceries: Dinner Reminder"
    trigger:
      - platform: time
        at: "16:00:00"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.butlergroceries_tonight
            state: "Nothing planned"
    action:
      - action: notify.mobile_app_trevors_iphone
        data:
          title: "🍳 Tonight's Dinner"
          message: "{{ states('sensor.butlergroceries_tonight') }}"
          data:
            url: "https://groceries.butlerfamily.com"

  - id: butlergroceries_no_dinner_planned
    alias: "Butler Groceries: No Dinner Planned"
    trigger:
      - platform: time
        at: "14:00:00"
    condition:
      - condition: state
        entity_id: sensor.butlergroceries_tonight
        state: "Nothing planned"
    action:
      - action: notify.mobile_app_trevors_iphone
        data:
          title: "📅 No Dinner Planned Tonight"
          message: "Open Butler Groceries to plan or start swiping!"
          data:
            url: "https://groceries.butlerfamily.com/swipe"

  - id: butlergroceries_shopping_reminder
    alias: "Butler Groceries: Weekly Shopping Reminder"
    trigger:
      - platform: time
        at: "10:00:00"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - action: notify.mobile_app_trevors_iphone
        data:
          title: "🛒 Shopping List Ready"
          message: "{{ states('sensor.butlergroceries_shopping') }}"
          data:
            url: "https://groceries.butlerfamily.com/shopping"
